lib/log

diff --git a/lib/log b/lib/log
--- a/lib/log
+++ b/lib/log
@@ -2,13 +2,13 @@
 
 declare -F log &>/dev/null || {
   
-  declare -gxi log_level=0
-  declare log_level(){ log_level=${1:-0}; }
-
-  declare log_colors=false && [ -t 1 ] && [[ "$TERM" == *color* ]] && log_colors=true
-  
-  declare -gxA log_style=();
-  log_style(){ [ $log_colors ] && log_style["$1"]="\033[38;2;${4//,/;}m$2 " || log_style["$1"]="$2 "; }
+  declare -gx LOG_COLOR=false && [ -t 1 ] && [[ "$TERM" == *color* ]] && LOG_COLOR=true
+  declare -gxi LOG_LEVEL=0
+  declare -gxA log_level=() log_style=();
+  log_style(){
+    log_level[$1]=$2
+    [ $LOG_COLOR ] && log_style["$1"]="\033[38;2;${4//,/;}m$3 " || log_style["$1"]="$3 ";
+  }
   log_style --code 0 ➲ 91,155,213 # detailed information for debugging
   log_style --exec 0 ▸ 91,155,213 # detailed information for debugging
   log_style --note 1 • 80,80,80
@@ -21,10 +21,16 @@ declare -F log &>/dev/null || {
 
   # write a (colored) message to stderr
   # @usage: log <level> <message>
+  #         Example - logging specific command: `log --exec ls -la`
   log(){
-    [ "$1" != --exec ] && (( log_level >= $2 )) || return 0
-    local style="" && [ "${log_style["$1"]}" ] && style="${log_style["$1"]}"
-    echo -e "${style}$*${style+\033[0m}" >&2
-    [ "$1" == --exec ] && $@
+    local output exec=false && [ "$1" == --exec ] && exec=true
+    [ $exec ] || { (( LOG_LEVEL >= "${log_level[$1]}" )) || return 0; }
+    local style="" && [ "${log_style["$1"]}" ] && { style="${log_style["$1"]}"; shift;}
+    if [ $exec ]; then
+      output=$( "$@" 2>&1 )
+      [ $? == 0 ] && echo -e "${log_style[--good]}\033[1m$@\033[22m\n$output${style+\033[0m}" >&2 || echo -e "${log_style[--fail]}\033[1m$@\033[22m\n$output${style+\033[0m}" >&2
+    else
+      echo -e "${style}$*${style+\033[0m}" >&2
+    fi
   }
 }
